import{a as f,i as s,S as y}from"./assets/vendor-vwbIfzmB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();function g(r){const o="50194034-6daf74b2774d983dcc54e4495",n="https://pixabay.com/api/",a={key:o,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true"};return f.get(n,{params:a}).then(e=>e.data).catch(e=>{s.error({title:"Error",message:"Illegal operation"})})}document.querySelector(".loader");const p=document.querySelector(".gallery"),h=new y(".gallery a",{captionsData:"alt",captionDelay:250});function L(r){const o=r.map(({webformatURL:n,largeImageURL:a,tags:e,likes:t,views:i,comments:m,downloads:d})=>`<li class="gallery-item">
        <a class="gallery-link" href="${a}">
        <img class="img-item" src="${n}" alt="${e}"/>
        </a>
        <p>Likes <span>${t}</span></p>
        <p>View <span>${i}</span></p>
        <p>Comments <span>${m}</span></p>
        <p>Downloads <span>${d}</span></p>
        </li>`).join("");p.innerHTML=o,h.refresh()}function c(){p.innerHTML=""}function S(r){r.style.display="block"}function u(r){r.style.display="none"}document.querySelector(".gallery");const b=document.querySelector(".form");document.querySelector('[type="submit"]');const q=document.querySelector('[name="search-text"]'),l=document.querySelector(".loader");b.addEventListener("submit",function(r){r.preventDefault();const o=q.value.trim();if(o===""){s.warning({title:"Caution",message:"You forgot important data"});return}S(l),c(),g(o).then(n=>{if(n.hits.length===0){s.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!"}),c();return}L(n.hits),u(l)}).catch(n=>{console.error("Error fetching data:",n),s.error({title:"Error",message:"Error."})}).finally(()=>{u(l)})});
//# sourceMappingURL=index.js.map
