import{a as f,i as s,S as y}from"./assets/vendor-vwbIfzmB.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();function g(o){const n="50194034-6daf74b2774d983dcc54e4495",r="https://pixabay.com/api/",a={key:n,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"};return f.get(r,{params:a}).then(e=>e.data).catch(e=>{s.error({title:"Error",message:"Illegal operation"})})}document.querySelector(".loader");const d=document.querySelector(".gallery"),h=new y(".gallery a",{captionsData:"alt",captionDelay:250});function L(o){const n=o.map(({webformatURL:r,largeImageURL:a,tags:e,likes:t,views:i,comments:p,downloads:m})=>`<li class="gallery-item">
        <a class="gallery-link" href="${a}">
        <img class="img-item" src="${r}" alt="${e}"/>
        </a>
        <p>Likes <span>${t}</span></p>
        <p>View <span>${i}</span></p>
        <p>Comments <span>${p}</span></p>
        <p>Downloads <span>${m}</span></p>
        </li>`).join("");d.innerHTML=n,h.refresh()}function c(){d.innerHTML=""}function S(o){o.classList.remove("hidden")}function u(o){o.classList.add("hidden")}document.querySelector(".gallery");const q=document.querySelector(".form");document.querySelector('[type="submit"]');const b=document.querySelector('[name="search-text"]'),l=document.querySelector(".loader");q.addEventListener("submit",function(o){o.preventDefault();const n=b.value.trim();if(n===""){s.warning({title:"Caution",message:"You forgot important data"}),c(res.hits);return}S(l),c(),g(n).then(r=>{if(r.hits.length===0){s.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!"}),c(r.hits);return}L(r.hits),u(l)}).catch(r=>{console.error("Error fetching data:",r),u(l),s.error({title:"Error",message:"Error."})})});
//# sourceMappingURL=index.js.map
